### ISSUE TITLE
It hungs when run in mac M2 chip env.

### ISSUE THREAD

**Issue by chen1195585098** [SlashScreen/skelerealms#10]
Hi, @SlashScreen 

Sorry for disturbing, but each time I run this proj in my godot editor, it will hung for few minutes until I cancel it. And I do not see any alert information in the console. So, I wonder how can I debug this proj and locate more useful infomation for this issue?

my dev environment:
godot 4.0.3
mac air with M2 chip.

**Comment by SlashScreen** [comment]
The chip should not matter, since it's written in GDScript.
The first thing I noticed is that your version is 4.0.3; Skelerealms relies on static variables in gdscript, so only 4.1+ is supported.
Also, I have pushed some changes I have made in the mast few months to this repository just now, so you can use the new version if you wish; I believe it fixes a few issues I had with loading.

**Comment by chen1195585098** [comment]
> The chip should not matter, since it's written in GDScript. The first thing I noticed is that your version is 4.0.3; Skelerealms relies on static variables in gdscript, so only 4.1+ is supported. Also, I have pushed some changes I have made in the mast few months to this repository just now, so you can use the new version if you wish; I believe it fixes a few issues I had with loading.

Thanks for you reply, I upgrade my godot and it works well now :)
